import type { JobApplication } from "./types"

export const MOCK_APPLICATIONS: JobApplication[] = [
  {
    id: "1",
    resumeId: "resume-1",
    url: "https://nofluffjobs.com/job/senior-devops-engineer-allegro",
    source: "nofluffjobs",
    company: "Allegro",
    position: "Senior DevOps Engineer",
    location: "Warsaw, Remote",
    salary: "22,000 - 28,000 PLN",
    techStack: ["Kubernetes", "Terraform", "AWS", "GitLab CI", "Python"],
    responsibilities: ["Build and maintain CI/CD pipelines", "Manage Kubernetes clusters"],
    description: "We are looking for a Senior DevOps Engineer to join our platform team...",
    appliedAt: new Date("2025-01-10"),
    resumeVersion: 2,
    status: "interview_scheduled",
    responded: true,
    respondedAt: new Date("2025-01-12"),
    interviewScheduled: true,
    offerReceived: false,
    rejected: false,
    notes: "HR called, technical interview next week",
  },
  {
    id: "2",
    resumeId: "resume-1",
    url: "https://justjoin.it/offers/ing-bank-sre-engineer",
    source: "justjoin",
    company: "ING Bank",
    position: "SRE Engineer",
    location: "Warsaw",
    salary: "18,000 - 24,000 PLN",
    techStack: ["Kubernetes", "Prometheus", "Grafana", "Go", "Ansible"],
    responsibilities: ["Monitor and improve system reliability", "Build observability stack"],
    description: "Join our SRE team to build reliable banking infrastructure...",
    appliedAt: new Date("2025-01-08"),
    resumeVersion: 2,
    status: "responded",
    responded: true,
    respondedAt: new Date("2025-01-11"),
    interviewScheduled: false,
    offerReceived: false,
    rejected: false,
  },
  {
    id: "3",
    resumeId: "resume-1",
    url: "https://pracuj.pl/praca/devops-engineer-cd-projekt",
    source: "pracuj",
    company: "CD Projekt",
    position: "DevOps Engineer",
    location: "Warsaw",
    salary: "15,000 - 22,000 PLN",
    techStack: ["Jenkins", "Docker", "Linux", "Bash", "Perforce"],
    responsibilities: ["Maintain game build pipelines", "Support development teams"],
    description: "Help us ship the next Witcher game with reliable CI/CD...",
    appliedAt: new Date("2025-01-05"),
    resumeVersion: 1,
    status: "rejected",
    responded: true,
    rejected: true,
    rejectedAt: new Date("2025-01-09"),
    interviewScheduled: false,
    offerReceived: false,
  },
  {
    id: "4",
    resumeId: "resume-1",
    url: "https://nofluffjobs.com/job/platform-engineer-docplanner",
    source: "nofluffjobs",
    company: "Docplanner",
    position: "Platform Engineer",
    location: "Warsaw, Remote",
    salary: "20,000 - 26,000 PLN",
    techStack: ["AWS", "Terraform", "Kubernetes", "ArgoCD", "Datadog"],
    responsibilities: ["Build and maintain cloud infrastructure", "Implement IaC"],
    description: "Build and maintain our cloud infrastructure...",
    appliedAt: new Date("2025-01-12"),
    resumeVersion: 2,
    status: "applied",
    responded: false,
    interviewScheduled: false,
    offerReceived: false,
    rejected: false,
  },
  {
    id: "5",
    resumeId: "resume-1",
    url: "https://linkedin.com/jobs/view/cloud-engineer-revolut",
    source: "linkedin",
    company: "Revolut",
    position: "Cloud Engineer",
    location: "Krakow, Remote",
    salary: "25,000 - 35,000 PLN",
    techStack: ["GCP", "Kubernetes", "Terraform", "Python", "BigQuery"],
    responsibilities: ["Scale cloud infrastructure", "Optimize costs"],
    description: "Scale our cloud infrastructure to millions of users...",
    appliedAt: new Date("2025-01-14"),
    resumeVersion: 2,
    status: "viewed",
    responded: false,
    interviewScheduled: false,
    offerReceived: false,
    rejected: false,
  },
  {
    id: "6",
    resumeId: "resume-1",
    url: "https://justjoin.it/offers/samsung-devops-lead",
    source: "justjoin",
    company: "Samsung R&D",
    position: "DevOps Team Lead",
    location: "Warsaw",
    salary: "28,000 - 38,000 PLN",
    techStack: ["Jenkins", "Kubernetes", "AWS", "Python", "Helm"],
    responsibilities: ["Lead DevOps team", "Define CI/CD strategy"],
    description: "Lead a team of DevOps engineers building TV software CI/CD...",
    appliedAt: new Date("2025-01-13"),
    resumeVersion: 2,
    status: "offer",
    responded: true,
    interviewScheduled: true,
    offerReceived: true,
    rejected: false,
    offerAmount: "32,000 PLN + benefits",
    interviewNotes: "3 rounds: HR, Technical, Team Lead. Very positive feedback.",
  },
]
